<a href="https://colab.research.google.com/github/rtmonteiro/ia-2023-1/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Carregue a base iris e a separe em treino e teste usando 40% dos exemplos para teste. Reduza a base de treino para ter apenas os 24 exemplos iniciais e a de teste para ter apenas os 16 exemplos iniciais. Considere que o valor 1.5 representa um elemento ausente. Substitua as ocorrências de valores ausentes pelo valor mais frequente nas bases de treino e de teste reduzidas.

In [1]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

ds = datasets.load_iris()

X_train, X_test, y_train, y_test = train_test_split(ds.data, 
                    ds.target, test_size=0.4, random_state=0)

X_train = X_train[slice(24)]
X_test = X_test[slice(16)]

# print(X_train)
# print(X_test)

In [2]:
from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=1.5, strategy="most_frequent")
imp2 = SimpleImputer(missing_values=1.5, strategy="most_frequent")

print("Train")
print(imp.fit_transform(X_train))
print("Teste")
print(imp2.fit_transform(X_test))

Train
[[6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 4.2 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 4.2 0.4]
 [6.9 3.1 4.9 0.2]
 [4.6 3.1 4.2 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 0.2]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]]
Teste
[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 4.7 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.4]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.4]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.4]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]]


2. Utilize agora os mesmos valores mais frequentes usados na base de treino na base de teste do exercício 1.

In [3]:
imp.fit(X_train)
print(imp.transform(X_test))

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 4.2 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 0.2]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 0.2]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 0.2]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]]


3. Padronize a base de treino do exercício 1 e utilize os mesmos fatores de normalização para
padronizar a base de teste.

In [4]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaler = scaler.transform(X_train)
print('Train')
print(X_train_scaler)

X_test_scaler = scaler.transform(X_test)
print('\nTest')
print(X_test_scaler)

X_scaled = preprocessing.scale(X_train)
print ('\nMean: ', X_scaled.mean(axis=0))
print ('Standard Deviation: ', X_scaled.std(axis=0))

Train
[[ 0.33603962  0.76296356  0.52477983  0.64940905]
 [-1.15287438  0.08477373 -1.20624749 -1.2988181 ]
 [ 0.08788728 -0.81947938  0.88292342  1.0668863 ]
 [-0.16026505 -0.81947938  0.34570804  0.2319318 ]
 [-0.16026505 -0.36735282 -0.01243554  0.2319318 ]
 [-0.28434121 -1.27160593  0.22632685  0.2319318 ]
 [ 0.46011578 -0.14128955  0.58447043  0.37109089]
 [ 1.82495362  0.310837    1.42013879  0.92772721]
 [-0.53249355  1.44115338 -1.26593808 -1.2988181 ]
 [-1.77325521 -0.14128955 -1.50470047 -1.43797718]
 [ 0.83234428 -0.81947938  1.00230461  1.0668863 ]
 [-0.03618888 -0.14128955  0.34570804  0.09277272]
 [-0.40841738  0.76296356 -1.14655689 -1.2988181 ]
 [-0.03618888  3.02359632 -1.26593808 -1.02049994]
 [ 1.45272512  0.08477373  0.76354222  0.51024997]
 [-1.40102671  0.08477373 -1.26593808 -1.2988181 ]
 [ 0.21196345 -0.14128955  0.88292342  0.92772721]
 [-0.78064588 -1.27160593 -0.37057912 -0.04638636]
 [-1.40102671  0.76296356 -1.32562868 -1.15965902]
 [ 0.58419195 -1.94979576

4. Discretize a base Z_Train usando a estratégia de igual frequência nos intervalos e utilize os mesmos intervalos para discretizar a base Z_Test. Repita depois usando a estratégia de igual tamanho dos intervalos. Atenção: crie novas bases para não alterar a definição original de Z_Train e Z_Test.

In [5]:
est = preprocessing.KBinsDiscretizer(n_bins=[6, 3, 4, 2], 
                                     encode='ordinal').fit(X_train)
X_bin = est.transform(X_train)
print(X_bin)

X_bin_test = est.transform(X_test)
print(X_bin_test)

[[4. 2. 2. 1.]
 [1. 2. 1. 0.]
 [3. 0. 3. 1.]
 [2. 0. 2. 1.]
 [2. 0. 1. 1.]
 [2. 0. 1. 1.]
 [4. 1. 2. 1.]
 [5. 2. 3. 1.]
 [1. 2. 0. 0.]
 [0. 1. 0. 0.]
 [4. 0. 3. 1.]
 [3. 1. 2. 0.]
 [1. 2. 1. 0.]
 [3. 2. 0. 0.]
 [5. 2. 2. 1.]
 [0. 2. 0. 0.]
 [3. 1. 3. 1.]
 [1. 0. 1. 0.]
 [0. 2. 0. 0.]
 [4. 0. 2. 1.]
 [5. 2. 3. 1.]
 [3. 0. 2. 1.]
 [1. 1. 0. 0.]
 [5. 1. 3. 1.]]
[[3. 0. 3. 1.]
 [4. 0. 1. 0.]
 [2. 2. 0. 0.]
 [5. 0. 3. 1.]
 [1. 2. 0. 0.]
 [4. 2. 3. 1.]
 [1. 2. 0. 0.]
 [5. 2. 2. 1.]
 [5. 0. 2. 1.]
 [4. 0. 1. 1.]
 [4. 0. 3. 1.]
 [4. 2. 2. 1.]
 [4. 0. 2. 0.]
 [5. 0. 2. 1.]
 [4. 0. 2. 1.]
 [1. 2. 0. 0.]]


In [6]:
est = preprocessing.KBinsDiscretizer(n_bins=[6, 3, 4, 2], 
                    encode='ordinal', strategy='uniform').fit(X_train)
X_bin = est.transform(X_train)
print(X_bin)

[[3. 1. 2. 1.]
 [1. 1. 0. 0.]
 [3. 0. 3. 1.]
 [2. 0. 2. 1.]
 [2. 0. 2. 1.]
 [2. 0. 2. 1.]
 [3. 1. 2. 1.]
 [5. 1. 3. 1.]
 [2. 2. 0. 0.]
 [0. 1. 0. 0.]
 [4. 0. 3. 1.]
 [2. 1. 2. 0.]
 [2. 1. 0. 0.]
 [2. 2. 0. 0.]
 [5. 1. 3. 1.]
 [0. 1. 0. 0.]
 [3. 1. 3. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [3. 0. 2. 1.]
 [5. 1. 3. 1.]
 [2. 0. 2. 1.]
 [1. 1. 0. 0.]
 [5. 1. 3. 1.]]


5. Leia a base de dados breast cancer e execute 3 rodadas de validação cruzada aninhada 
estratificada, porém use padronização em todas as características da base. Use o classificador KNN com k = {1, 3, 5}. Apresente a acurácia obtida em cada fold de teste, assim como a média da acurácia, desvio padrão e intervalo de confiança.

In [7]:
import numpy as np
from sklearn import datasets
from scipy import stats
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

bc = datasets.load_breast_cancer()

X_train, X_test, y_train, y_test = train_test_split(bc.data, 
                    bc.target, test_size=0.4, random_state=0)


6. Crie um dataset com 5 exemplos com dados nominais para condições do dia com temperatura (baixa, média e alta), aparência (ensolarado, nublado, chuvoso) e vento (pouco, muito). Transforme os dados de temperatura e vento para o formato ordinal e o de aparência para o formato binário.

In [18]:
import pandas as pd

df = pd.DataFrame([
    ['alta', 'chuvoso', 'pouco'],
    ['alta', 'chuvoso', 'muito'],
    ['alta', 'nublado', 'pouco'],
    ['média', 'ensolarado', 'pouco'],
    ['baixa', 'ensolarado', 'pouco']
])

df.columns = ['temp', 'aparência', 'vento']
df

temp   aparência  vento
0   alta     chuvoso  pouco
1   alta     chuvoso  muito
2   alta     nublado  pouco
3  média  ensolarado  pouco
4  baixa  ensolarado  pouco

In [19]:
# Transforma temperatura em Nominal
enc = preprocessing.OrdinalEncoder()
enc.fit(df[['temp']])
df[['temp']] = enc.transform(df[['temp']])
df

temp   aparência  vento
0   0.0     chuvoso  pouco
1   0.0     chuvoso  muito
2   0.0     nublado  pouco
3   2.0  ensolarado  pouco
4   1.0  ensolarado  pouco

In [20]:
# Transforma vento em Nominal
enc = preprocessing.OrdinalEncoder()
enc.fit(df[['vento']])
df[['vento']] = enc.transform(df[['vento']])
df

temp   aparência  vento
0   0.0     chuvoso    1.0
1   0.0     chuvoso    0.0
2   0.0     nublado    1.0
3   2.0  ensolarado    1.0
4   1.0  ensolarado    1.0

In [21]:
# Transforma aparência em Binário
# data = np.asarray(df[["aparência"]])
# print('\n', data)
# encoder = preprocessing.OneHotEncoder(sparse_output=False)
# onehot = encoder.fit_transform(data)
# print('\n', onehot)

df = pd.get_dummies(df[['temp', 'aparência', 'vento']])
df

temp  vento  aparência_chuvoso  aparência_ensolarado  aparência_nublado
0   0.0    1.0                  1                     0                  0
1   0.0    0.0                  1                     0                  0
2   0.0    1.0                  0                     0                  1
3   2.0    1.0                  0                     1                  0
4   1.0    1.0                  0                     1                  0

7. Compare o desempenho em termos de acurácia do método PCA com três componentes com o método de seleção univariada de características usando análise de variância e selecionando 3 características no dataset wine. Use o classificador Vizinho Mais Próximo (k = 1) e o método de divisão percentual com 30% da base usada para teste.

In [24]:
from sklearn.decomposition import PCA
from sklearn import datasets

wine = datasets.load_wine()

X_train, X_test, y_train, y_test = train_test_split(
    wine.data, wine.target, test_size=0.3, random_state=0)

pca = PCA(n_components=3)
pca_tr = pca.fit(X_train)
X_ts = pca_tr.transform(X_test)
# print(X_test)
# print(X_ts)

In [27]:
from sklearn.feature_selection import SelectKBest

wine_X_train, wine_X_test, wine_y_train, wine_y_test = train_test_split(
    wine.data, wine.target, test_size=0.4, random_state=0)
wine_X_b = SelectKBest(k=3).fit_transform(wine_X_train, y_train)
# print (wine_X_train)
# print (wine_X_b)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
oneNN = KNeighborsClassifier(n_neighbors=1)
oneNN.fit(wine_X_b, wine_y_train)



8. Obtenha o desempenho (acurácia média, desvio padrão e intervalo de confiança a 95%) do
método de seleção multivariada de características com seleção sequencial para frente e selecionando 3 características no dataset wine. Use padronização, o classificador K Vizinhos Mais Próximo (k = 1, 3 ou 5) e o método de validação cruzada aninhada com 3 repetições de 10 folds.

Obtenha o desempenho (acurácia média, desvio padrão e intervalo de confiança a 95%)



método de seleção multivariada de características com seleção sequencial para frente

In [28]:
from sklearn.neighbors import KNeighborsClassifier

oneNN = KNeighborsClassifier(n_neighbors=1)

from sklearn.feature_selection import SequentialFeatureSelector

sfs_forward = SequentialFeatureSelector(oneNN, n_features_to_select=2,
                direction='forward').fit(X_train, y_train)

feature_names = np.array(wine.feature_names)

print("Features selected by forward sequential selection: ")
print(feature_names[sfs_forward.get_support()])

Features selected by forward sequential selection: 
['alcohol' 'flavanoids']


Use padronização

o classificador K Vizinhos Mais Próximo (k = 1, 3 ou 5)

o método de validação cruzada aninhada com 3 repetições de 10 folds