<a href="https://colab.research.google.com/github/rtmonteiro/ia-2023-1/blob/main/lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Carregue a base iris e a separe em treino e teste usando 40% dos exemplos para teste. Reduza a base de treino para ter apenas os 24 exemplos iniciais e a de teste para ter apenas os 16 exemplos iniciais. Considere que o valor 1.5 representa um elemento ausente. Substitua as ocorrências de valores ausentes pelo valor mais frequente nas bases de treino e de teste reduzidas.

In [18]:
from sklearn import datasets
from sklearn.model_selection import train_test_split

ds = datasets.load_iris()

X_train, X_test, y_train, y_test = train_test_split(ds.data, 
                    ds.target, test_size=0.4, random_state=0)

X_train = X_train[slice(24)]
X_test = X_test[slice(16)]

# print(X_train)
# print(X_test)

In [ ]:
from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=1.5, strategy="most_frequent")
imp2 = SimpleImputer(missing_values=1.5, strategy="most_frequent")

print("Train")
print(imp.fit_transform(X_train))
print("Teste")
print(imp2.fit_transform(X_test))

2. Utilize agora os mesmos valores mais frequentes usados na base de treino na base de teste do exercício 1.

In [22]:
imp.fit(X_train)
print(imp.transform(X_test))

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 4.2 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 0.2]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 0.2]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 0.2]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]]


3. Padronize a base de treino do exercício 1 e utilize os mesmos fatores de normalização para
padronizar a base de teste.

In [26]:
from sklearn import preprocessing

scaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaler = scaler.transform(X_train)
print('Train')
print(X_train_scaler)

X_test_scaler = scaler.transform(X_test)
print('\nTest')
print(X_test_scaler)

X_scaled = preprocessing.scale(X_train)
print ('\nMean: ', X_scaled.mean(axis=0))
print ('Standard Deviation: ', X_scaled.std(axis=0))

Train
[[ 0.33603962  0.76296356  0.52477983  0.64940905]
 [-1.15287438  0.08477373 -1.20624749 -1.2988181 ]
 [ 0.08788728 -0.81947938  0.88292342  1.0668863 ]
 [-0.16026505 -0.81947938  0.34570804  0.2319318 ]
 [-0.16026505 -0.36735282 -0.01243554  0.2319318 ]
 [-0.28434121 -1.27160593  0.22632685  0.2319318 ]
 [ 0.46011578 -0.14128955  0.58447043  0.37109089]
 [ 1.82495362  0.310837    1.42013879  0.92772721]
 [-0.53249355  1.44115338 -1.26593808 -1.2988181 ]
 [-1.77325521 -0.14128955 -1.50470047 -1.43797718]
 [ 0.83234428 -0.81947938  1.00230461  1.0668863 ]
 [-0.03618888 -0.14128955  0.34570804  0.09277272]
 [-0.40841738  0.76296356 -1.14655689 -1.2988181 ]
 [-0.03618888  3.02359632 -1.26593808 -1.02049994]
 [ 1.45272512  0.08477373  0.76354222  0.51024997]
 [-1.40102671  0.08477373 -1.26593808 -1.2988181 ]
 [ 0.21196345 -0.14128955  0.88292342  0.92772721]
 [-0.78064588 -1.27160593 -0.37057912 -0.04638636]
 [-1.40102671  0.76296356 -1.32562868 -1.15965902]
 [ 0.58419195 -1.94979576

4. Discretize a base Z_Train usando a estratégia de igual frequência nos intervalos e utilize os mesmos intervalos para discretizar a base Z_Test. Repita depois usando a estratégia de igual tamanho dos intervalos. Atenção: crie novas bases para não alterar a definição original de Z_Train e Z_Test.

In [32]:
est = preprocessing.KBinsDiscretizer(n_bins=[6, 3, 4, 2], 
                                     encode='ordinal').fit(X_train)
X_bin = est.transform(X_train)
print(X_bin)

X_bin_test = est.transform(X_test)
print(X_bin_test)

[[4. 2. 2. 1.]
 [1. 2. 1. 0.]
 [3. 0. 3. 1.]
 [2. 0. 2. 1.]
 [2. 0. 1. 1.]
 [2. 0. 1. 1.]
 [4. 1. 2. 1.]
 [5. 2. 3. 1.]
 [1. 2. 0. 0.]
 [0. 1. 0. 0.]
 [4. 0. 3. 1.]
 [3. 1. 2. 0.]
 [1. 2. 1. 0.]
 [3. 2. 0. 0.]
 [5. 2. 2. 1.]
 [0. 2. 0. 0.]
 [3. 1. 3. 1.]
 [1. 0. 1. 0.]
 [0. 2. 0. 0.]
 [4. 0. 2. 1.]
 [5. 2. 3. 1.]
 [3. 0. 2. 1.]
 [1. 1. 0. 0.]
 [5. 1. 3. 1.]]
[[3. 0. 3. 1.]
 [4. 0. 1. 0.]
 [2. 2. 0. 0.]
 [5. 0. 3. 1.]
 [1. 2. 0. 0.]
 [4. 2. 3. 1.]
 [1. 2. 0. 0.]
 [5. 2. 2. 1.]
 [5. 0. 2. 1.]
 [4. 0. 1. 1.]
 [4. 0. 3. 1.]
 [4. 2. 2. 1.]
 [4. 0. 2. 0.]
 [5. 0. 2. 1.]
 [4. 0. 2. 1.]
 [1. 2. 0. 0.]]


In [33]:
est = preprocessing.KBinsDiscretizer(n_bins=[6, 3, 4, 2], 
                    encode='ordinal', strategy='uniform').fit(X_train)
X_bin = est.transform(X_train)
print(X_bin)

[[3. 1. 2. 1.]
 [1. 1. 0. 0.]
 [3. 0. 3. 1.]
 [2. 0. 2. 1.]
 [2. 0. 2. 1.]
 [2. 0. 2. 1.]
 [3. 1. 2. 1.]
 [5. 1. 3. 1.]
 [2. 2. 0. 0.]
 [0. 1. 0. 0.]
 [4. 0. 3. 1.]
 [2. 1. 2. 0.]
 [2. 1. 0. 0.]
 [2. 2. 0. 0.]
 [5. 1. 3. 1.]
 [0. 1. 0. 0.]
 [3. 1. 3. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [3. 0. 2. 1.]
 [5. 1. 3. 1.]
 [2. 0. 2. 1.]
 [1. 1. 0. 0.]
 [5. 1. 3. 1.]]


5. Leia a base de dados breast cancer e execute 3 rodadas de validação cruzada aninhada 
estratificada, porém use padronização em todas as características da base. Use o classificador KNN com k = {1, 3, 5}. Apresente a acurácia obtida em cada fold de teste, assim como a média da acurácia, desvio padrão e intervalo de confiança.

In [ ]:
import numpy as np
from sklearn import datasets
from scipy import stats
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

bc = datasets.load_breast_cancer()

X_train, X_test, y_train, y_test = train_test_split(bc.data, 
                    bc.target, test_size=0.4, random_state=0)


